# Generated by Django 5.0.6 on 2024-05-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0002_plant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='garden_bed',
        ),
        migrations.AddField(
            model_name='plant',
            name='garden_bed',
            field=models.ManyToManyField(to='garden.gardenbed'),
        ),
    ]
